runtime: nodejs
env: flex

env_variables:
  BUCKET_NAME: "fundhub"

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
  
handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
